name: Database Integration Tests with Experimental Features

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

permissions: read-all

jobs:
  build:
    name: Build, run database integration tests, with experimental features
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [8, 17]
    runs-on: ${{ matrix.os }}
    steps:

# SETUP BUILD ENVIRONMENT
    - id: prepare-maven-build
      name: Prepare Maven build
      uses: sualeh/prepare-maven-build@e4169f1bc1d00ee0cce0bf26f6076d9d25d4dc03 # pin@v1.3.2
      with:
        java-version: ${{ matrix.java }}

    - id: install-graphviz
      name: Install graphviz
      if:
      shell: bash
      run: |
        # Install Graphviz
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get install graphviz
        elif [ "$RUNNER_OS" == "Windows" ]; then
          choco install graphviz
        elif [ "$RUNNER_OS" == "macOS" ]; then
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install graphviz
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
        dot -V

# BUILD AND TEST
    - id: build-test
      name: Build and run database integration tests
      env:
        TZ: GMT
      shell: bash
      run: |
        # Build
        mvn \
          --no-transfer-progress \
          --batch-mode \
          -DSC_EXPERIMENTAL=true \
          -Dheavydb \
          -pl !schemacrawler-sqlserver,!schemacrawler-examplecode \
          clean package
